### ISSUE TITLE
tornado optional dependency

### ISSUE THREAD

**Issue by jucacrispim** [jucacrispim/mongomotor#1]
tornado should be an optional dependency and should be installed only as an extra.

**Comment by jucacrispim** [comment]
Hello @Mr0Null 

I saw you are using a copy of mongomotor with tornado dependency removed. I just released the version 0.11.0 of mongomotor and this version includes these changes here that make tornado an optional dependency. I think that will work for you. Feel free to use if you wish.

Thanks

**Comment by mavahedinia** [comment]
Thanks a lot! I am just looking for a way to integrate it in Sanic framework just like flask_mongoengine. currently it works but didn't satisfied me.
